# 4 MUESTREO

### 4.1 Muestreo Estadístico

### $\bf{Población:}$ conjunto de sujetos/objetos con una o varias características que podemos medir. $\newline$

### $\bf{Muestra:}$ subconjunto de una población.

### Cuando la selección de una muestra de la población se realiza de manera que todas las muestras del mismo tamaño sean equiprobables, se denomina $\bf{muestreo}$ $\bf{aleaorio}$.

### Consideremos una urna de 100 bolas numeradas del 1 al 100:

<img src="urna.png">

### Suponga que se requiere una muestra aleatoria con reposición/reemplazamiento/repetición de tamaño 16.

<img src="urna2.png">

Para generar la muestra aleatoria en python usaremos la función $\bf{random.choices}$ del módulo $\bf{random}$.

In [5]:
import random

esferas = list(range(1, 101))
muestra = random.choices(esferas, k=16)
muestra

[32, 32, 52, 88, 85, 21, 96, 5, 56, 43, 45, 7, 98, 7, 26, 82]

Para el siguiente ejemplo usaremos una base de datos denominada iris, la cual importamos usando $\textbf{Seaborn}$. La tabla de datos iris contiene 150 flores de 3 especies diferentes: setosa, versicolor y virginica.

In [1]:
import seaborn as sns
iris = sns.load_dataset('iris')

In [2]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### Si quisiéramos una muestra de 20 flores con reposición, haríamos lo siguiente:

In [3]:
muestra1 = iris.sample(20, replace=True)
muestra1

     sepal_length  sepal_width  petal_length  petal_width     species
25            5.0          3.0           1.6          0.2      setosa
97            6.2          2.9           4.3          1.3  versicolor
108           6.7          2.5           5.8          1.8   virginica
66            5.6          3.0           4.5          1.5  versicolor
68            6.2          2.2           4.5          1.5  versicolor
104           6.5          3.0           5.8          2.2   virginica
89            5.5          2.5           4.0          1.3  versicolor
2             4.7          3.2           1.3          0.2      setosa
10            5.4          3.7           1.5          0.2      setosa
61            5.9          3.0           4.2          1.5  versicolor
75            6.6          3.0           4.4          1.4  versicolor
87            6.3          2.3           4.4          1.3  versicolor
137           6.4          3.1           5.5          1.8   virginica
46            5.1          3.8           1.6          0.2      setosa
62            6.0          2.2           4.0          1.0  versicolor
43            5.0          3.5           1.6          0.6      setosa
5             5.4          3.9           1.7          0.4      setosa
8             4.4          2.9           1.4          0.2      setosa
76            6.8          2.8           4.8          1.4  versicolor
85            6.0          3.4           4.5          1.6  versicolor

### Otra manera de extraer nuestra muestra sería repetir 15 veces el proceso de sacar una bola de la urna pero ahora sin devolverla. En este caso se habla de una $\bf{muestra}$ $\bf{aleatoria}$ $\bf{sin}$ $\bf{reposición}$.

### Para obtener una muestra de 10 flores sin reposición, haríamos los pasos siguientes:

In [12]:
muestra2= iris.sample(20, replace=False)
muestra2

     sepal_length  sepal_width  petal_length  petal_width     species
126           6.2          2.8           4.8          1.8   virginica
12            4.8          3.0           1.4          0.1      setosa
84            5.4          3.0           4.5          1.5  versicolor
51            6.4          3.2           4.5          1.5  versicolor
137           6.4          3.1           5.5          1.8   virginica
70            5.9          3.2           4.8          1.8  versicolor
147           6.5          3.0           5.2          2.0   virginica
78            6.0          2.9           4.5          1.5  versicolor
98            5.1          2.5           3.0          1.1  versicolor
23            5.1          3.3           1.7          0.5      setosa
117           7.7          3.8           6.7          2.2   virginica
7             5.0          3.4           1.5          0.2      setosa
114           5.8          2.8           5.1          2.4   virginica
102           7.1          3.0           5.9          2.1   virginica
129           7.2          3.0           5.8          1.6   virginica
125           7.2          3.2           6.0          1.8   virginica
80            5.5          2.4           3.8          1.1  versicolor
119           6.0          2.2           5.0          1.5   virginica
103           6.3          2.9           5.6          1.8   virginica
107           7.3          2.9           6.3          1.8   virginica

### Supongamos que los individuos de una población vienen dados en forma de una lista ordenada. El $\bf{muestreo}$ $\bf{sistemático}$ consiste en tomarlos a intervalos constantes escogiendo al azar el primer individuo que elegimos.

<img src="urna3.png">

### Ahora calculemos una muestra aleatoria sistemática de la tabla de datos iris de tamaño 10.

In [6]:
import numpy as np 

primera_flor = random.randint(0, 151)
incremento = 15

flores_elegidas = np.arange(primera_flor, primera_flor + incremento * 10, incremento)
print(flores_elegidas)

flores_elegidas_sis=flores_elegidas%150
print(flores_elegidas_sis)

[ 95 110 125 140 155 170 185 200 215 230]
[ 95 110 125 140   5  20  35  50  65  80]

In [7]:
muestra3=iris.iloc[flores_elegidas_sis, :]
muestra3

     sepal_length  sepal_width  petal_length  petal_width     species
95            5.7          3.0           4.2          1.2  versicolor
110           6.5          3.2           5.1          2.0   virginica
125           7.2          3.2           6.0          1.8   virginica
140           6.7          3.1           5.6          2.4   virginica
5             5.4          3.9           1.7          0.4      setosa
20            5.4          3.4           1.7          0.2      setosa
35            5.0          3.2           1.2          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
65            6.7          3.1           4.4          1.4  versicolor
80            5.5          2.4           3.8          1.1  versicolor

### Cuando la población está clasificada en estratos (grupos), se toma una muestra aleatoria de cada estrato y se unen en una muestra global. A este proceso se le llama $\bf{muestreo}$ $\bf{aleatorio}$ $\bf{estratificado}$.

<img src="urna4.png">

### En el caso de la tabla de datos iris está estratificada en tres grupos: setosa, versicolor y virginica. Cada estrato está compuesto por 50 flores de la misma especie. Vamos a hallar una muestra de tamaño 12 hallando tres muestras de tamaño 4 de cada especie (estrato) con reposición y después juntaremos la tres submuestras para obtener la muestra global.

In [4]:
 iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [5]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [6]:
setosa=iris.query('species == "setosa"')
setosa.describe()

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000    50.000000
mean        5.00600     3.428000      1.462000     0.246000
std         0.35249     0.379064      0.173664     0.105386
min         4.30000     2.300000      1.000000     0.100000
25%         4.80000     3.200000      1.400000     0.200000
50%         5.00000     3.400000      1.500000     0.200000
75%         5.20000     3.675000      1.575000     0.300000
max         5.80000     4.400000      1.900000     0.600000

In [7]:
versicolor=iris.query('species == "versicolor"')

In [8]:
virginica=iris.query('species == "virginica"')

In [9]:
muestra_setosa = setosa.sample(4, replace=True)
muestra_versicolor = versicolor.sample(4, replace=True)
muestra_virginica = virginica.sample(4, replace=True)

In [10]:
muestra_setosa

    sepal_length  sepal_width  petal_length  petal_width species
22           4.6          3.6           1.0          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
24           4.8          3.4           1.9          0.2  setosa

In [11]:
import pandas as pd
muestra4=pd.concat([muestra_setosa, muestra_versicolor, muestra_virginica])
muestra4

     sepal_length  sepal_width  petal_length  petal_width     species
22            4.6          3.6           1.0          0.2      setosa
4             5.0          3.6           1.4          0.2      setosa
34            4.9          3.1           1.5          0.2      setosa
24            4.8          3.4           1.9          0.2      setosa
55            5.7          2.8           4.5          1.3  versicolor
58            6.6          2.9           4.6          1.3  versicolor
77            6.7          3.0           5.0          1.7  versicolor
92            5.8          2.6           4.0          1.2  versicolor
102           7.1          3.0           5.9          2.1   virginica
122           7.7          2.8           6.7          2.0   virginica
104           6.5          3.0           5.8          2.2   virginica
119           6.0          2.2           5.0          1.5   virginica

In [15]:
muestra5=reset_index(drop=True)
muestra5

    sepal_length  sepal_width  petal_length  petal_width     species
0            6.0          2.2           5.0          1.5   virginica
1            5.0          3.6           1.4          0.2      setosa
2            7.1          3.0           5.9          2.1   virginica
3            4.6          3.6           1.0          0.2      setosa
4            6.7          3.0           5.0          1.7  versicolor
5            4.9          3.1           1.5          0.2      setosa
6            6.6          2.9           4.6          1.3  versicolor
7            5.7          2.8           4.5          1.3  versicolor
8            4.8          3.4           1.9          0.2      setosa
9            5.8          2.6           4.0          1.2  versicolor
10           7.7          2.8           6.7          2.0   virginica
11           6.5          3.0           5.8          2.2   virginica

In [17]:
muestra5.to_json('muestra6.json', index=False)

### $\textbf{Ejercicio}$ De la base de datos "titanic" de la biblioteca seaborn, generar una muestra aleatoria sin remplazo, otra con remplazo, una sistemática, y finalmente una estratificada considerando la variable "sex".

In [17]:
titanic = sns.load_dataset('titanic')

In [18]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True