# Curso: Probabilidad y Estadística
## Maestría en Ciencias de Datos
## Otoño 2025

# Prueba de Hipótesis

Una prueba de hipótesis es descrita por las siguientes componentes:
\begin{align}
(X_1, \ldots, X_n; H_0, H_1; G)
\end{align}
donde $X_1, \ldots, X_n$ es una muestra aleatoria, $H_0$ y $H_1$ son hipótesis concernientes a la distribución de probabilidad de la población, y $G$ es un subconjunto de $\mathbb{R}^n$.

El conjunto $G$ se denomina región crítica o de rechazo. Si $(X_1=x_1, X_2=x_2, \ldots, X_n=x_n)\in G\subset \mathbb{R}^n$ entonces se acepta $H_1$ en caso contrario se acepta $H_0$.

$\textbf{Ejemplo}$ Considere el siguiente juego de hipótesis
\begin{align}
H_0: X\sim N(500, 50)
\end{align}

\begin{align}
H_1: X\sim N(490, 50)
\end{align}

equivalentemente, $H_0:\mu=500$ vs $H_1:\mu=490$.

Regla de Decisión: Si $X_1, X_2\leq 496$ entonces aceptamos $H_1$, i.e. $G=\{(x_1, x_2)\in \mathbb{R}^2:x_1,x_2\leq 496\}$.

<img src="cuadrohip.png">

Hipótesis Unilateral/Bilateral.

Los posibles escenarios al realizar una prueba de hipótesis son los siguientes:

<img src="cuadro-error.png">

## Contrastes de hipótesis para el parámetro $\mu$ de una variable normal con $\sigma$ conocida

$H_0:\mu=\mu_0$ vs $H_1:\mu> \mu_0$

Estadístico:
\begin{align}
Z=\frac{\bar{X}-\mu}{\sigma/\sqrt{n}}\sim N(0,1)
\end{align}

La regla consistirá en rechazar $H_0$ si el estadístico de contraste $Z$ es mayor a un umbral ($z$) por determinar, el cual se obtiene vía el nivel de significancia ($\alpha$).

\begin{align}
\alpha=P(Z>z)\Longleftrightarrow 1-\alpha=P(Z\leq z).
\end{align}

es decir, $z=z_{1-\alpha}$.

<img src="r1.png">

En conclusión, Rechazar $H_0$, si el estadístico de contraste
\begin{align}
Z_0=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}>z_{1-\alpha}
\end{align}

Observe que también queda determinado un intervalo de confianza para $\mu$:

$$Z<z_{1-\alpha}\Longrightarrow \frac{\bar{X}-\mu}{\sigma/\sqrt{n}}<z_{1-\alpha}$$

$$\mu\in (\bar{X}-z_{1-\alpha}\frac{\sigma}{\sqrt{n}}, \infty)$$

## El $p$-valor

El $p$-valor o valor crítico de un contraste es la probabilidad que el estadístico de contraste tome un un valor tan extremo o más que el que se ha observado, dado que $H_0$ es verdadera. En el caso anterior se tendría:

\begin{align}
p=\mathbb{P}(Z\geq Z_0|H_0)
\end{align}

##  El método de los seis pasos

1. Establecer la hipótesis nula $H_0$ y la hipótesis alternativa $H_1$.

2. Fijar un nivel de significacia $\alpha$.

3. Seleccionar el estadístico de contraste apropiado.

4. Calcular el valor del estadístico de contraste a partir de los datos muestrales.

5. Calcular el $p$-valor del contraste.

6. Decisión: rechazar $H_0$ en favor de  $H_1$ si el $p$-valor es más pequeño que $\alpha$; en caso contrario, aceptar $H_0$.

## 8.2 Contrastes de hipótesis para el parámetro $\mu$ de una variable normal con $\sigma$ desconocida

En este caso debemos considerar al estadístico $T$:
$$ T=\frac{\bar{X}-\mu}{\frac{S}{\sqrt{n}}}\sim T-Student(n-1)$$

$\textbf{Ejemplo 8.2.1}$ Se espera que el nivel de colesterol en un grupo de pacientes bajo un determinado tratamiento se distribuya normalmente con media 220 mg/dl.

Se toma una muestra de 9 pacientes, y se miden sus niveles: 203, 229, 215, 220, 223, 233, 208, 228,209.
Contrastar la hipótesis que esta muestra efectivamente proviene de una población con media 220 mg/dl.
$H_0: \mu=220$ vs $H_1:\mu \neq 220$.

In [5]:
import numpy as np

colesterol = np.array([203, 229, 215, 220, 223, 233, 208, 228, 209])

media_muestral = np.mean(colesterol)
desv_muestral = np.std(colesterol, ddof=1)  
n = len(colesterol)
estadistico_contraste = (media_muestral - 220) / (desv_muestral / np.sqrt(n))

estadistico_contraste

np.float64(-0.38009147051646663)

In [9]:
import scipy.stats as stats
2*(1-stats.t.cdf(abs(estadistico_contraste), df=8))

np.float64(0.7137700471397652)

In [10]:
from scipy.stats import ttest_1samp
result = ttest_1samp(colesterol, popmean=220, alternative='two-sided') 
result

TtestResult(statistic=np.float64(-0.38009147051646663), pvalue=np.float64(0.7137700471397653), df=np.int64(8))

In [16]:
help(ttest_1samp)

Help on function ttest_1samp in module scipy.stats._stats_py:

ttest_1samp(a, popmean, axis=0, nan_policy='propagate', alternative='two-sided', *, keepdims=False)
    Calculate the T-test for the mean of ONE group of scores.

    This is a test for the null hypothesis that the expected value
    (mean) of a sample of independent observations `a` is equal to the given
    population mean, `popmean`.

    Parameters
    ----------
    a : array_like
        Sample observation.
    popmean : float or array_like
        Expected value in null hypothesis. If array_like, then its length along
        `axis` must equal 1, and it must otherwise be broadcastable with `a`.
    axis : int or None, default: 0
        If an int, the axis of the input along which to compute the statistic.
        The statistic of each axis-slice (e.g. row) of the input will appear in a
        corresponding element of the output.
        If ``None``, the input will be raveled before computing the statistic.
    nan_policy : {'propagate', 'omit', 'raise'}
        Defines how to handle input NaNs.

        - ``propagate``: if a NaN is present in the axis slice (e.g. row) along
          which the  statistic is computed, the corresponding entry of the output
          will be NaN.
        - ``omit``: NaNs will be omitted when performing the calculation.
          If insufficient data remains in the axis slice along which the
          statistic is computed, the corresponding entry of the output will be
          NaN.
        - ``raise``: if a NaN is present, a ``ValueError`` will be raised.
    alternative : {'two-sided', 'less', 'greater'}, optional
        Defines the alternative hypothesis.
        The following options are available (default is 'two-sided'):

        * 'two-sided': the mean of the underlying distribution of the sample
          is different than the given population mean (`popmean`)
        * 'less': the mean of the underlying distribution of the sample is
          less than the given population mean (`popmean`)
        * 'greater': the mean of the underlying distribution of the sample is
          greater than the given population mean (`popmean`)
    keepdims : bool, default: False
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will broadcast correctly against the input array.

    Returns
    -------
    result : `~scipy.stats._result_classes.TtestResult`
        An object with the following attributes:

        statistic : float or array
            The t-statistic.
        pvalue : float or array
            The p-value associated with the given alternative.
        df : float or array
            The number of degrees of freedom used in calculation of the
            t-statistic; this is one less than the size of the sample
            (``a.shape[axis]``).

            .. versionadded:: 1.10.0

        The object also has the following method:

        confidence_interval(confidence_level=0.95)
            Computes a confidence interval around the population
            mean for the given confidence level.
            The confidence interval is returned in a ``namedtuple`` with
            fields `low` and `high`.

            .. versionadded:: 1.10.0

    Notes
    -----
    The statistic is calculated as ``(np.mean(a) - popmean)/se``, where
    ``se`` is the standard error. Therefore, the statistic will be positive
    when the sample mean is greater than the population mean and negative when
    the sample mean is less than the population mean.

    Beginning in SciPy 1.9, ``np.matrix`` inputs (not recommended for new
    code) are converted to ``np.ndarray`` before the calculation is performed. In
    this case, the output will be a scalar or ``np.ndarray`` of appropriate shape
    rather than a 2D ``np.matrix``. Similarly, while masked elements of masked
    arrays are ignored, the output will be a scalar or ``np.ndarray`` rather than a
    masked array with ``mask=False``.

    Examples
    --------
    Suppose we wish to test the null hypothesis that the mean of a population
    is equal to 0.5. We choose a confidence level of 99%; that is, we will
    reject the null hypothesis in favor of the alternative if the p-value is
    less than 0.01.

    When testing random variates from the standard uniform distribution, which
    has a mean of 0.5, we expect the data to be consistent with the null
    hypothesis most of the time.

    >>> import numpy as np
    >>> from scipy import stats
    >>> rng = np.random.default_rng()
    >>> rvs = stats.uniform.rvs(size=50, random_state=rng)
    >>> stats.ttest_1samp(rvs, popmean=0.5)
    TtestResult(statistic=2.456308468440, pvalue=0.017628209047638, df=49)

    As expected, the p-value of 0.017 is not below our threshold of 0.01, so
    we cannot reject the null hypothesis.

    When testing data from the standard *normal* distribution, which has a mean
    of 0, we would expect the null hypothesis to be rejected.

    >>> rvs = stats.norm.rvs(size=50, random_state=rng)
    >>> stats.ttest_1samp(rvs, popmean=0.5)
    TtestResult(statistic=-7.433605518875, pvalue=1.416760157221e-09, df=49)

    Indeed, the p-value is lower than our threshold of 0.01, so we reject the
    null hypothesis in favor of the default "two-sided" alternative: the mean
    of the population is *not* equal to 0.5.

    However, suppose we were to test the null hypothesis against the
    one-sided alternative that the mean of the population is *greater* than
    0.5. Since the mean of the standard normal is less than 0.5, we would not
    expect the null hypothesis to be rejected.

    >>> stats.ttest_1samp(rvs, popmean=0.5, alternative='greater')
    TtestResult(statistic=-7.433605518875, pvalue=0.99999999929, df=49)

    Unsurprisingly, with a p-value greater than our threshold, we would not
    reject the null hypothesis.

    Note that when working with a confidence level of 99%, a true null
    hypothesis will be rejected approximately 1% of the time.

    >>> rvs = stats.uniform.rvs(size=(100, 50), random_state=rng)
    >>> res = stats.ttest_1samp(rvs, popmean=0.5, axis=1)
    >>> np.sum(res.pvalue < 0.01)
    1

    Indeed, even though all 100 samples above were drawn from the standard
    uniform distribution, which *does* have a population mean of 0.5, we would
    mistakenly reject the null hypothesis for one of them.

    `ttest_1samp` can also compute a confidence interval around the population
    mean.

    >>> rvs = stats.norm.rvs(size=50, random_state=rng)
    >>> res = stats.ttest_1samp(rvs, popmean=0)
    >>> ci = res.confidence_interval(confidence_level=0.95)
    >>> ci
    ConfidenceInterval(low=-0.3193887540880017, high=0.2898583388980972)

    The bounds of the 95% confidence interval are the
    minimum and maximum values of the parameter `popmean` for which the
    p-value of the test would be 0.05.

    >>> res = stats.ttest_1samp(rvs, popmean=ci.low)
    >>> np.testing.assert_allclose(res.pvalue, 0.05)
    >>> res = stats.ttest_1samp(rvs, popmean=ci.high)
    >>> np.testing.assert_allclose(res.pvalue, 0.05)

    Under certain assumptions about the population from which a sample
    is drawn, the confidence interval with confidence level 95% is expected
    to contain the true population mean in 95% of sample replications.

    >>> rvs = stats.norm.rvs(size=(50, 1000), loc=1, random_state=rng)
    >>> res = stats.ttest_1samp(rvs, popmean=0)
    >>> ci = res.confidence_interval()
    >>> contains_pop_mean = (ci.low < 1) & (ci.high > 1)
    >>> contains_pop_mean.sum()
    953

$\textbf{Conclusión:}$ Como que el $p$-valor$>0.1$, no podemos rechazar que el nivel medio de colesterol en plasma sea igual a 220 mg/dl.

In [13]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

<img src="SepalPetal.jpg" width="30%">

$\textbf{Ejemplo 8.2.2}$ Dada una muestra de tamaño 40 de flores de la tabla de datos iris, podemos considerar que la media de la longitud del sépalo es mayor que 5.7.

In [5]:
flores_elegidas = iris.sample(40, replace=True)
flores_elegidas

     sepal_length  sepal_width  petal_length  petal_width     species
137           6.4          3.1           5.5          1.8   virginica
74            6.4          2.9           4.3          1.3  versicolor
62            6.0          2.2           4.0          1.0  versicolor
30            4.8          3.1           1.6          0.2      setosa
65            6.7          3.1           4.4          1.4  versicolor
61            5.9          3.0           4.2          1.5  versicolor
122           7.7          2.8           6.7          2.0   virginica
3             4.6          3.1           1.5          0.2      setosa
22            4.6          3.6           1.0          0.2      setosa
6             4.6          3.4           1.4          0.3      setosa
23            5.1          3.3           1.7          0.5      setosa
0             5.1          3.5           1.4          0.2      setosa
25            5.0          3.0           1.6          0.2      setosa
0             5.1          3.5           1.4          0.2      setosa
94            5.6          2.7           4.2          1.3  versicolor
20            5.4          3.4           1.7          0.2      setosa
131           7.9          3.8           6.4          2.0   virginica
111           6.4          2.7           5.3          1.9   virginica
3             4.6          3.1           1.5          0.2      setosa
12            4.8          3.0           1.4          0.1      setosa
26            5.0          3.4           1.6          0.4      setosa
49            5.0          3.3           1.4          0.2      setosa
142           5.8          2.7           5.1          1.9   virginica
31            5.4          3.4           1.5          0.4      setosa
60            5.0          2.0           3.5          1.0  versicolor
72            6.3          2.5           4.9          1.5  versicolor
62            6.0          2.2           4.0          1.0  versicolor
103           6.3          2.9           5.6          1.8   virginica
132           6.4          2.8           5.6          2.2   virginica
141           6.9          3.1           5.1          2.3   virginica
63            6.1          2.9           4.7          1.4  versicolor
2             4.7          3.2           1.3          0.2      setosa
31            5.4          3.4           1.5          0.4      setosa
68            6.2          2.2           4.5          1.5  versicolor
34            4.9          3.1           1.5          0.2      setosa
105           7.6          3.0           6.6          2.1   virginica
29            4.7          3.2           1.6          0.2      setosa
70            5.9          3.2           4.8          1.8  versicolor
131           7.9          3.8           6.4          2.0   virginica
46            5.1          3.8           1.6          0.2      setosa

In [6]:
long_sepalo_muestra = flores_elegidas['sepal_length'].values
long_sepalo_muestra

array([6.4, 6.4, 6. , 4.8, 6.7, 5.9, 7.7, 4.6, 4.6, 4.6, 5.1, 5.1, 5. ,
       5.1, 5.6, 5.4, 7.9, 6.4, 4.6, 4.8, 5. , 5. , 5.8, 5.4, 5. , 6.3,
       6. , 6.3, 6.4, 6.9, 6.1, 4.7, 5.4, 6.2, 4.9, 7.6, 4.7, 5.9, 7.9,
       5.1])

### Prueba T de una muestra

In [7]:
mu = 5.7
ttest_1samp(long_sepalo_muestra, mu, alternative='greater')

TtestResult(statistic=0.2144548599406232, pvalue=0.4156548814948619, df=39)

¿Conclusión?

$\textbf{Ejemplo 8.2.3}$ Consideremos la siguiente base de datos. Dicha tabla de datos contiene información acerca de 189 recién nacidos en cierto hospital en el año 1986.

In [11]:
import pandas as pd
datanac=pd.read_csv('data-birth.csv')
datanac.head()

   low  age  lwt  race  smoke  ptl  ht  ui  ftv   bwt
0    0   19  182     2      0    0   0   1    0  2523
1    0   33  155     3      0    0   0   0    3  2551
2    0   20  105     1      1    0   0   0    1  2557
3    0   21  108     1      1    0   0   1    2  2594
4    0   18  107     1      1    0   0   1    0  2600

Vamos a contrastar si la proporción de madres fumadoras supera el 30%:

$H_0:$ $p=0.3$

$H_1:$ $p>0.3$

In [12]:
madres_elegidas = datanac.sample(30, replace=True)
madres_elegidas

     low  age  lwt  race  smoke  ptl  ht  ui  ftv   bwt
102    0   24  110     3      0    1   0   0    0  3770
129    0   45  123     1      0    0   0   0    1  4990
130    1   28  120     3      1    1   0   1    0   709
164    1   18  110     2      1    1   0   0    0  2296
86     0   19  105     3      0    0   0   0    0  3572
129    0   45  123     1      0    0   0   0    1  4990
28     0   26  168     2      1    0   0   0    0  2920
99     0   30  137     1      0    0   0   0    1  3699
97     0   19  147     1      1    0   0   0    0  3651
54     0   19  115     3      0    0   0   0    0  3175
7      0   17  103     3      0    0   0   0    1  2637
168    1   31  102     1      1    1   0   0    1  2353
109    0   16  170     2      0    0   0   0    4  3860
99     0   30  137     1      0    0   0   0    1  3699
88     0   36  175     1      0    0   0   0    0  3600
175    1   30  142     1      1    1   0   0    0  2410
97     0   19  147     1      1    0   0   0    0  3651
105    0   25  241     2      0    0   1   0    0  3790
145    1   20  150     1      1    0   0   0    2  1928
45     0   18   90     1      1    0   0   1    0  3062
81     0   32  170     1      0    0   0   0    0  3473
121    0   26  160     3      0    0   0   0    0  4054
22     0   36  202     1      0    0   0   0    1  2836
151    1   19  102     1      0    0   0   0    2  2082
25     0   28  167     1      0    0   0   0    0  2877
144    1   25   92     1      1    0   0   0    0  1928
92     0   19  235     1      1    0   1   0    0  3629
139    1   21  165     1      1    0   1   0    1  1790
51     0   23  128     3      0    0   0   0    0  3104
120    0   20  158     1      0    0   0   0    1  3997

In [13]:
numero_madres_fumadoras = np.sum(madres_elegidas['smoke'] == 1)
numero_madres_fumadoras

12

In [14]:
from scipy.stats import binomtest

resultado_prueba = binomtest(numero_madres_fumadoras, 30, p=0.3, alternative='greater')
resultado_prueba

BinomTestResult(k=12, n=30, alternative='greater', statistic=0.4, pvalue=0.15932179468792518)

Conclusión: Dada la muestra no es posible rechazar la hipóteis nula. Es decir, no hay evidencia suficiente para rechazar que la proporción de madres fumadoras es o.3.

## Contrastes de hipótesis para el parámetro $\sigma$ de una variable con distribución normal

En el caso de hipótesis referente a la varianza (desviación estandar) de una población se utiliza el estadístico:
$$ \chi^2_{n-1}=\frac{(n-1)S^2}{\sigma^2}$$
el cual tiene una distribución $\chi^2$ con n-1 grados de libertad.

$\textbf{Ejemplo}$ Verifiquemos que si la varianza de la amplitud del sépalo de las flores de la base de datos iris es menor que 0.2. Considere un nivel de significancia de 0.05.
$H_0:\sigma^2= 0.2$ vs $H_1=\sigma^2< 0.2$

In [10]:
from scipy.stats import chi2

flores_elegidas_chi = iris.sample(40, replace=False)

varianza_muestral = flores_elegidas_chi['sepal_width'].var()
n = len(flores_elegidas_chi)
varianza_hipotetica = 0.2
estadistico_prueba = (n - 1) * varianza_muestral / varianza_hipotetica

valor_critico = chi2.ppf(0.05, df=n-1)  
print(valor_critico)
print(estadistico_prueba)

25.695390399574777
29.479999999999993

Concluimos por tanto, que en base a la muestra no tenemos evidencias suficientes para aceptar que la varianza de la amplitud del sépalo sea menor que 0.2.

### Ejercicio: Elaborar el código para concluir la prueba en base al p-valor.

 ## Contrastes de hipótesis para dos muestras

En este contexto se busca comparar el valor de un parámetro en dos poblaciones. De este modo se requiere una muestra para cada población. En este caso las hipótesis alternativas son:

$\bullet$  las medias muestrales son distintas.

$\bullet$ la media de la primera muestra es mayor que la segunda.

$\bullet$ la media de la primera muestra es menor que la segunda.

$\textbf{Ejemplo}$ Supongamos que nos planteamos la siguiente pregunta: ¿la media de la longitud del pétalo es distinta para las flores de las especies setosa y versicolor?

In [17]:
setosa=iris.query('species == "setosa"')
versicolor=iris.query('species == "versicolor"')

In [18]:
muestra_setosa = setosa.sample(30, replace=True)
muestra_versicolor = versicolor.sample(30, replace=True)

In [19]:
from scipy.stats import ttest_ind
t_statistic, p_value = ttest_ind(muestra_setosa['petal_length'], muestra_versicolor['petal_length'], alternative='two-sided')
print(p_value)

6.4614513231954e-33

In [21]:
ttest_ind?

### Tarea: Realizar la prueba para comparar varianzas entre dos poblaciones.